changelog:
  categories:
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Fixes"
      labels:
        - "bug"
        - "bugfix"
        - "fix"
    - title: "Maintenance"
      labels:
        - "chore"
        - "maintenance"
        - "ci"
        - "docs"
  exclude:
    labels:
      - "skip-changelog"
    authors:
      - "dependabot[bot]"
