package routing

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDetectDnsmasqConfDirPrefersExisting(t *testing.T) {
	base := t.TempDir()
	first := filepath.Join(base, "dnsmasq.d")
	second := filepath.Join(base, "dnsmasq.dhcp.conf.d")
	if err := os.MkdirAll(second, 0o755); err != nil {
		t.Fatalf("mkdir second: %v", err)
	}
	if err := os.MkdirAll(first, 0o755); err != nil {
		t.Fatalf("mkdir first: %v", err)
	}

	dir, err := detectDnsmasqConfDir([]string{first, second})
	if err != nil {
		t.Fatalf("detect dir: %v", err)
	}
	if dir != first {
		t.Fatalf("expected first candidate %s, got %s", first, dir)
	}
}

func TestDetectDnsmasqConfDirCreatesPrimaryIfMissing(t *testing.T) {
	base := t.TempDir()
	first := filepath.Join(base, "dnsmasq.d")
	second := filepath.Join(base, "dnsmasq.dhcp.conf.d")

	dir, err := detectDnsmasqConfDir([]string{first, second})
	if err != nil {
		t.Fatalf("detect dir: %v", err)
	}
	if dir != first {
		t.Fatalf("expected created first dir %s, got %s", first, dir)
	}
	if info, err := os.Stat(first); err != nil || !info.IsDir() {
		t.Fatalf("expected created directory %s", first)
	}
}

func TestGenerateDnsmasqConf(t *testing.T) {
	m := NewDnsmasqManagerWithPath(filepath.Join(t.TempDir(), "split-vpn-webui.conf"), nil)
	groups := []DomainGroup{
		{Name: "Gaming", Domains: []string{"*.roblox.com", "rbxcdn.com"}},
		{Name: "Streaming-SG", Domains: []string{"hbo.com", "max.com"}},
	}
	content := m.GenerateDnsmasqConf(groups)

	for _, expected := range []string{
		"# Generated by split-vpn-webui. Do not edit.",
		"ipset=/roblox.com/",
		"ipset=/rbxcdn.com/",
		"ipset=/hbo.com/",
		"ipset=/max.com/",
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("expected generated config to contain %q\n%s", expected, content)
		}
	}
}

func TestWriteAndReloadDnsmasq(t *testing.T) {
	mock := &MockExec{
		Outputs: map[string][]byte{"pidof dnsmasq": []byte("1234\n")},
	}
	configPath := filepath.Join(t.TempDir(), "split-vpn-webui.conf")
	m := NewDnsmasqManagerWithPath(configPath, mock)

	content := "ipset=/example.com/svpn_example_v4,svpn_example_v6\n"
	if err := m.WriteDnsmasqConf(content); err != nil {
		t.Fatalf("write conf: %v", err)
	}
	bytes, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read conf: %v", err)
	}
	if string(bytes) != content {
		t.Fatalf("unexpected file contents: %q", string(bytes))
	}

	if err := m.ReloadDnsmasq(); err != nil {
		t.Fatalf("reload dnsmasq: %v", err)
	}
	if len(mock.RunCalls) == 0 || strings.Join(mock.RunCalls[0], " ") != "kill -HUP 1234" {
		t.Fatalf("expected first reload command kill -HUP 1234, got %#v", mock.RunCalls)
	}
}
